### ISSUE TITLE
`--` syntax wrapped with Prettier proseWrap option

### ISSUE THREAD

**Issue by karlhorky** [nkzw-tech/remdx#13]
The `--` syntax for adding front matter to each slide is made invalid by [the Prettier Prose Wrap option](https://prettier.io/docs/en/options.html#prose-wrap), when it is set to `'never'` or `'always'`:

`prettier.config.mjs`

```js
/** @type {import('prettier').Config} */
const prettierConfig = {
  proseWrap: 'always', // 💥 destroys in-slide front matter
  singleQuote: true,
};

export default prettierConfig;
```

**Before**

```mdx
import sights from './sights.tsx';

export { Components } from './Components.tsx';
export { Themes } from './Themes.tsx';

--
image: tokyo.jpg
--

# Welcome to ReMDXx

---

# Slide 2
```

**After**

```mdx
import sights from './sights.tsx';

export { Components } from './Components.tsx';
export { Themes } from './Themes.tsx';

-- image: tokyo.jpg --

# Welcome to ReMDXx

---

# Slide 2
```

https://github.com/nkzw-tech/remdx/assets/1935696/a4a8e020-d48d-484f-b6ab-46f7cd74c780

This causes the slide front matter to become visible text in the slide:

![Screenshot 2024-02-10 at 15 55 09](https://github.com/nkzw-tech/remdx/assets/1935696/2d48c292-d0d7-47ab-9610-353406bab872)

**Comment by karlhorky** [comment]
## Workaround

Add a new Prettier config file in the slide deck directory without a `proseWrap` option:

`slides/prettier.config.mjs`

```js
/** @type {import('prettier').Config} */
const prettierConfig = {
  singleQuote: true,
};

export default prettierConfig;
```

**Comment by cpojer** [comment]
This is not really a ReMDX concern since it pertains to how prettier formats Markdown. The template doesn't ship with prettier at this time, so unless we add it to the template it doesn't really make sense to ship a default prettier config.

I actually have to admit I didn't know this was configurable. I ran into this a few times while making slide decks. My recommendation is to always leave an empty newline before and after config entries.

**Comment by karlhorky** [comment]
## Workaround 2

> always leave an empty newline before and after config entries

Ah great! So this is another workaround - adding empty lines after the opening `--` and before the closing `--`:

```diff
 import sights from './sights.tsx';

 export { Components } from './Components.tsx';
 export { Themes } from './Themes.tsx';

 --
+
 image: tokyo.jpg
+
 --

 # Welcome to ReMDXx

 ---

 # Slide 2
```

**Comment by karlhorky** [comment]
Also opened a PR to switch the template to also use these newlines:

- #15
