### ISSUE TITLE
Upgrade `create-remdx` template to Vite 5

### ISSUE THREAD

**Issue by karlhorky** [nkzw-tech/remdx#14]
`create-remdx` currently uses Vite `^4.0.0`:

https://github.com/nkzw-tech/remdx/blob/68c4a945026a22efb846532a389536a77be49257/packages/create-remdx/template/package.json#L15

Maybe this could be changed to Vite v5

**Comment by cpojer** [comment]
Released 0.9.0.

**Comment by karlhorky** [comment]
Great thanks!
